seo:
  site_name: Jodlerklub Echo vom Mythen Schwyz
  title: Jodlerklub Echo vom Mythen Schwyz | Traditioneller Schwyzer Naturjuuz
  description: Der Jodlerklub Echo vom Mythen Schwyz pflegt seit 1928 den traditionellen Schwyzer Naturjuuz und tritt an Konzerten, Jodlerabenden, Gottesdiensten und Vereinsanlässen auf.
  keywords: Jodlerklub Echo vom Mythen, Echo vom Mythen, Schwyz, Jodlerklub Schwyz, Naturjuuz, Naturjodel, Schwyzer Naturjuuz, Jodeln, Jodlerabend, Schweizer Tradition, Volksmusik
  social_image: /images/echo-vom-mythen-banner-bild.JPG
  author: Jodlerklub Echo vom Mythen Schwyz
  favicon_image: /images/favicon.png

social:
  instagram_url: https://www.instagram.com/echovommythen/
  facebook_url:
  pinterest_url:
  linkedin_url:
  spotify_url:
  applemusic_url:
design:
  dark-text_color: '#343756'
  medium-text_color: '#8A293A'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#343756'
  medium_color: '#8A293A'
  light_color: '#f7f5f3'
  v-light_color: '#f9f9f9'
  featured_color: '#6495ed'
  accent_color: '#a74a4a'
